# Generated by Django 6.0.3 on 2026-03-29 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('candidat', 'Candidat'), ('recruteur', 'Recruteur'), ('admin', 'Administrateur')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='custom_user_set', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='custom_user_set', to='auth.permission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Recruteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_entreprise', models.CharField(max_length=150)),
                ('secteur_activite', models.CharField(max_length=100)),
                ('localisation', models.CharField(max_length=150)),
                ('ville', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=255)),
                ('site_web', models.URLField(blank=True)),
                ('telephone', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('date_creation_entreprise', models.DateField(blank=True, null=True)),
                ('taille_entreprise', models.CharField(max_length=50)),
                ('registre_commerce', models.FileField(upload_to='documents/recruteurs/')),
                ('certificat_immatriculation', models.FileField(upload_to='documents/recruteurs/')),
                ('patente', models.FileField(upload_to='documents/recruteurs/')),
                ('valide_par_admin', models.BooleanField(default=False)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('motif_rejet', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recruteur', to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='Candidat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField()),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('nationalite', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=20)),
                ('ville', models.CharField(max_length=100)),
                ('statut_matrimonial', models.CharField(choices=[('celibataire', 'Célibataire'), ('marie', 'Marié(e)'), ('divorce', 'Divorcé(e)')], max_length=20)),
                ('handicap', models.BooleanField(default=False)),
                ('langue_parlee', models.CharField(max_length=200)),
                ('secteur_activite', models.CharField(max_length=100)),
                ('dernier_poste', models.CharField(max_length=150)),
                ('derniere_entreprise', models.CharField(max_length=150)),
                ('competences', models.TextField()),
                ('cv', models.FileField(upload_to='documents/candidats/cv/')),
                ('diplome', models.FileField(upload_to='documents/candidats/diplomes/')),
                ('lettre_motivation', models.FileField(upload_to='documents/candidats/lettres/')),
                ('piece_identite', models.FileField(upload_to='documents/candidats/identite/')),
                ('profil_complete', models.BooleanField(default=False)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candidat', to='users.user')),
            ],
        ),
    ]
