# Generated by Django 6.0 on 2026-04-04 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_recruiter_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruteur',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='documents/recruteurs/logos/'),
        ),
    ]
