# Generated by Django 6.0.3 on 2026-04-05 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_recruteur_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruteur',
            name='logo',
            field=models.ImageField(upload_to='documents/recruteurs/logos/'),
        ),
    ]
