# Generated by Django 6.0.3 on 2026-04-10 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_recruteur_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidat',
            name='photo_profil',
            field=models.ImageField(blank=True, null=True, upload_to='documents/candidats/photos/'),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='qualifications',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='lettre_motivation',
            field=models.FileField(blank=True, null=True, upload_to='documents/candidats/lettres/'),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='note_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='favori',
            name='raison',
            field=models.TextField(blank=True),
        ),
    ]
