# Generated by Django 6.0.3 on 2026-04-10 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_candidat_photo_profil_alter_annonce_qualifications_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidature',
            name='comportement_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidature',
            name='entretien_rh_accepte_le',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidature',
            name='entretien_rh_date_prevue',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidature',
            name='entretien_rh_demande_le',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidature',
            name='motif_rejet_auto',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='candidature',
            name='rapport_etape1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='candidature',
            name='rapport_etape2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='candidature',
            name='score_etape1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidature',
            name='score_etape2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidature',
            name='score_final',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidature',
            name='transcription_ia',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='statut',
            field=models.CharField(choices=[('soumise', 'Soumise'), ('analyse_en_cours', 'Analyse en cours'), ('rejetee_auto', 'Rejetée automatiquement'), ('etape_2', 'Entretien IA disponible'), ('entretien_ia', 'Entretien IA en cours'), ('selectionne', 'Sélectionné'), ('entretien_rh', 'Entretien RH demandé'), ('entretien_rh_accepte', 'Entretien RH accepté'), ('valide', 'Validé'), ('rejetee', 'Rejetée'), ('acceptee', 'Acceptée'), ('acceptee_offre', 'Offre acceptée'), ('shortlistee', 'Shortlistée'), ('en_attente', 'En attente')], default='soumise', max_length=30),
        ),
    ]
